spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    password:
    username: sa
    hikari:
      auto-commit: false
    schema: classpath:init-schema.sql
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    properties.hibernate.format_sql: true
    open-in-view: false
    properties:
      hibernate:
        connection:
          provider_disables_autocommit: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true

logging:
  level:
    com.nobblecrafts.challenge.foodordering: DEBUG

server:
  port:  8080

checkout-service:
  api-url: http://localhost:8081

checkout-redis:
  port: 6379
  host: localhost